#!/usr/bin/env python3
"""Keep the public publishing docs aligned with the plugin's stable entry points."""

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
FILES = [ROOT / "README.md", ROOT / "doc" / "plan.md", ROOT / "doc" / "skills" / "publish-skills.md"]
FACTS = {
    "default remote mode": "githubPackages",
    "reusable workflow": ".github/workflows/publish.yml",
    "generated workflow marker": "# Generated by PublishPlugin one-click publish",
    "config prefix": "publish.*",
    "config skill": "skills/enter-publish-config/",
    "run skill": "skills/enter-publish-run/",
}


def main() -> int:
    missing_files = [str(path.relative_to(ROOT)) for path in FILES if not path.is_file()]
    if missing_files:
        print("Missing documentation files: " + ", ".join(missing_files), file=sys.stderr)
        return 1
    content = "\n".join(path.read_text(encoding="utf-8") for path in FILES)
    missing = [f"{label}: {value}" for label, value in FACTS.items() if value not in content]
    if missing:
        print("Documentation consistency check failed:", file=sys.stderr)
        for item in missing:
            print(f"- {item}", file=sys.stderr)
        return 1
    print("publish plugin documentation facts are consistent")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
