package custom.android.plugin.config

import java.io.File

object GitHubActionsWorkflowWriter {
    const val GENERATED_MARKER = "# Generated by PublishPlugin configureCentralPublish"

    fun writeWorkflow(
        rootDir: File,
        modulePath: String,
        moduleName: String,
        namespace: String,
        publishingType: String,
        workflowPath: String,
        workflowUses: String,
        overwrite: Boolean
    ): File {
        val path = workflowPath.ifBlank { ".github/workflows/publish-central-$moduleName.yml" }
        val workflowFile = File(rootDir, path)
        if (workflowFile.exists()) {
            val existing = workflowFile.readText()
            if (!existing.contains(GENERATED_MARKER) && !overwrite) {
                throw IllegalStateException(
                    "${workflowFile.path} already exists and was not generated by PublishPlugin. Use -PoverwriteWorkflow=true to replace it."
                )
            }
        }
        workflowFile.parentFile?.mkdirs()
        workflowFile.writeText(
            listOf(
                GENERATED_MARKER,
                "name: Publish Maven Central",
                "",
                "on:",
                "  workflow_dispatch:",
                "",
                "jobs:",
                "  publish:",
                "    uses: ${workflowUses.ifBlank { "Entertech/PublishPlugin/.github/workflows/central-publish.yml@main" }}",
                "    secrets: inherit",
                "    with:",
                "      module: \"$modulePath\"",
                "      publish_target: \"central\"",
                "      namespace: \"$namespace\"",
                "      publishing_type: \"$publishingType\"",
                ""
            ).joinToString(System.lineSeparator())
        )
        return workflowFile
    }
}
