package custom.android.plugin.config

import java.io.File

object GitHubActionsWorkflowWriter {
    const val GENERATED_MARKER = "# Generated by PublishPlugin configurePublish"
    const val DEFAULT_WORKFLOW_USES = "Entertech/PublishPlugin/.github/workflows/publish.yml@main"
    private const val LEGACY_GENERATED_MARKER = "# Generated by PublishPlugin configureCentralPublish"
    private const val LEGACY_REUSABLE_WORKFLOW_REF = ".github/workflows/central-publish.yml@"
    private const val REUSABLE_WORKFLOW_REF = ".github/workflows/publish.yml@"

    fun defaultWorkflowPath(moduleName: String): String = ".github/workflows/publish-$moduleName.yml"

    fun legacyDefaultWorkflowPath(moduleName: String): String = ".github/workflows/publish-central-$moduleName.yml"

    fun isGeneratedWorkflow(content: String): Boolean {
        return content.contains(GENERATED_MARKER) || content.contains(LEGACY_GENERATED_MARKER)
    }

    fun normalizeWorkflowUses(workflowUses: String): String {
        return workflowUses.replace(LEGACY_REUSABLE_WORKFLOW_REF, REUSABLE_WORKFLOW_REF)
    }

    fun writeWorkflow(
        rootDir: File,
        modulePath: String,
        moduleName: String,
        publishTarget: String,
        namespace: String,
        publishingType: String,
        version: String,
        githubPackagesRepository: String,
        githubPackagesUrl: String,
        workflowPath: String,
        workflowUses: String,
        overwrite: Boolean
    ): File {
        val path = workflowPath.ifBlank { defaultWorkflowPath(moduleName) }
        val workflowFile = File(rootDir, path)
        if (workflowFile.exists()) {
            val existing = workflowFile.readText()
            if (!isGeneratedWorkflow(existing) && !overwrite) {
                throw IllegalStateException(
                    "${workflowFile.path} already exists and was not generated by PublishPlugin. Use -PoverwriteWorkflow=true to replace it."
                )
            }
        }
        workflowFile.parentFile?.mkdirs()
        val normalizedTarget = publishTarget.ifBlank { "github_packages" }
        val lines = mutableListOf(
            GENERATED_MARKER,
            "name: Publish Maven",
            "",
            "on:",
            "  workflow_dispatch:",
            "",
            "permissions:",
            "  contents: write",
            "  packages: write",
            "",
            "jobs:",
            "  publish:",
            "    uses: ${normalizeWorkflowUses(workflowUses.ifBlank { DEFAULT_WORKFLOW_USES })}",
            "    secrets: inherit",
            "    with:",
            "      module: \"$modulePath\"",
            "      publish_target: \"$normalizedTarget\"",
            "      version: \"$version\""
        )
        if (normalizedTarget == "central" || normalizedTarget == "all") {
            lines += "      namespace: \"$namespace\""
            lines += "      publishing_type: \"$publishingType\""
        }
        if (normalizedTarget == "github_packages" || normalizedTarget == "all") {
            lines += "      sync_readme: true"
            if (githubPackagesRepository.isNotBlank()) {
                lines += "      github_packages_repository: \"$githubPackagesRepository\""
            }
            if (githubPackagesUrl.isNotBlank()) {
                lines += "      github_packages_url: \"$githubPackagesUrl\""
            }
        }
        lines += ""
        workflowFile.writeText(lines.joinToString(System.lineSeparator()))
        return workflowFile
    }
}
