package custom.android.plugin;

import org.gradle.testkit.runner.GradleRunner;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class OneClickPublishTaskFunctionalTest {
    private static final String TEST_GRADLE_VERSION = "8.7";

    @Rule
    public TemporaryFolder temporaryFolder = new TemporaryFolder();

    @Test
    public void generatePublishConfigPreservesAndroidLocalProperties() throws Exception {
        File projectDir = createGradlePluginProject("");
        write(projectDir.toPath().resolve("local.properties"), "sdk.dir=/Users/example/Library/Android/sdk\n");

        gradleRunner(projectDir)
                .withArguments(":fixture:generatePublishConfig", "--stacktrace")
                .build();

        String localProperties = read(projectDir.toPath().resolve("local.properties"));
        assertTrue(localProperties.contains("sdk.dir=/Users/example/Library/Android/sdk"));
        assertTrue(localProperties.contains("publish.githubRepo="));
        assertTrue(localProperties.contains("publish.publishTarget="));
        assertTrue(localProperties.contains("publish.workflowUses="));
        assertTrue(read(projectDir.toPath().resolve(".gitignore")).contains("local.properties"));
    }

    @Test
    public void configurePublishGeneratesGitHubPackagesWorkflowByDefault() throws Exception {
        File projectDir = createGradlePluginProject(
                "publish.githubActions=true\n"
                        + "publish.workflowUses=Entertech/PublishPlugin/.github/workflows/central-publish.yml@main\n"
                        + "publish.githubSecrets=false\n"
        );

        gradleRunner(projectDir)
                .withArguments(":fixture:configurePublish", "--stacktrace")
                .build();

        Path workflow = projectDir.toPath().resolve(".github/workflows/publish-fixture.yml");
        String workflowContent = read(workflow);
        assertTrue(workflowContent.contains("# Generated by PublishPlugin configurePublish"));
        assertTrue(workflowContent.contains("name: Publish Maven"));
        assertTrue(workflowContent.contains("contents: write"));
        assertTrue(workflowContent.contains("packages: write"));
        assertTrue(workflowContent.contains("uses: Entertech/PublishPlugin/.github/workflows/publish.yml@main"));
        assertFalse(workflowContent.contains("central-publish.yml"));
        assertTrue(workflowContent.contains("module: \":fixture\""));
        assertTrue(workflowContent.contains("publish_target: \"github_packages\""));
        assertTrue(workflowContent.contains("publish_mode: \"release\""));
        assertTrue(workflowContent.contains("version: \"1.0.0\""));
        assertTrue(workflowContent.contains("sync_readme: true"));
        assertFalse(workflowContent.contains("namespace:"));
        assertFalse(workflowContent.contains("publishing_type:"));
    }

    @Test
    public void configurePublishCanGenerateCentralWorkflowWhenRequested() throws Exception {
        File projectDir = createGradlePluginProject(
                "publish.githubActions=true\n"
                        + "publish.publishTarget=central\n"
                        + "publish.workflowUses=Entertech/PublishPlugin/.github/workflows/publish.yml@main\n"
                        + "publish.centralNamespace=com.example\n"
                        + "publish.centralPublishingType=user_managed\n"
                        + "publish.githubSecrets=false\n"
        );

        gradleRunner(projectDir)
                .withArguments(":fixture:configurePublish", "--stacktrace")
                .build();

        Path workflow = projectDir.toPath().resolve(".github/workflows/publish-fixture.yml");
        String workflowContent = read(workflow);
        assertTrue(workflowContent.contains("publish_target: \"central\""));
        assertTrue(workflowContent.contains("publish_mode: \"release\""));
        assertTrue(workflowContent.contains("version: \"1.0.0\""));
        assertTrue(workflowContent.contains("sync_readme: true"));
        assertTrue(workflowContent.contains("namespace: \"com.example\""));
        assertTrue(workflowContent.contains("publishing_type: \"user_managed\""));
    }

    @Test
    public void oneClickTasksAreRegisteredForPublishModule() throws Exception {
        File projectDir = createGradlePluginProject("");

        String output = gradleRunner(projectDir)
                .withArguments(":fixture:tasks", "--all", "--stacktrace")
                .build()
                .getOutput();

        assertTrue(output.contains("generatePublishConfig"));
        assertTrue(output.contains("configurePublish"));
        assertTrue(output.contains("rollbackPublishSecrets"));
        assertTrue(output.contains("GeneratePublishConfigTask"));
        assertTrue(output.contains("ConfigurePublishTask"));
        assertTrue(output.contains("RollbackPublishSecretsTask"));
        assertTrue(output.contains("generateCentralPublishConfig"));
        assertTrue(output.contains("GenerateCentralPublishConfigTask"));
        assertTrue(output.contains("configureCentralPublish"));
        assertTrue(output.contains("ConfigureCentralPublishTask"));
        assertTrue(output.contains("rollbackCentralPublishSecrets"));
        assertTrue(output.contains("RollbackCentralPublishSecretsTask"));
    }

    @Test
    public void configurePublishRejectsComponentFieldsInLocalProperties() throws Exception {
        File projectDir = createGradlePluginProject("publish.pomUrl=https://example.com\n");

        String output = gradleRunner(projectDir)
                .withArguments(":fixture:configurePublish", "--stacktrace")
                .buildAndFail()
                .getOutput();

        assertTrue(output.contains("PublishInfo"));
        assertFalse(Files.exists(projectDir.toPath().resolve(".github/workflows/publish-fixture.yml")));
    }

    @Test
    public void configurePublishDryRunDoesNotWriteFilesOrSecrets() throws Exception {
        File projectDir = createGradlePluginProject("");
        Path gpgKeyFile = projectDir.toPath().resolve("gpg-private.asc");
        write(gpgKeyFile, "private-key");
        write(projectDir.toPath().resolve("local.properties"),
                "publish.dryRun=true\n"
                        + "publish.githubActions=true\n"
                        + "publish.githubSecrets=true\n"
                        + "publish.githubRepo=OWNER/REPO\n"
                        + "publish.centralNamespace=com.example\n"
                        + "publish.centralPublishingType=user_managed\n"
                        + "publish.mavenCentralUsername=central-user\n"
                        + "publish.mavenCentralPassword=central-password\n"
                        + "publish.gpgKeyFile=" + gpgKeyFile.toAbsolutePath() + "\n"
                        + "publish.signingPassword=signing-password\n");
        File fakeGh = fakeGhScript(projectDir, "");

        gradleRunner(projectDir)
                .withArguments(
                        ":fixture:configurePublish",
                        "-PghExecutable=" + fakeGh.getAbsolutePath(),
                        "--stacktrace"
                )
                .build();

        assertFalse(Files.exists(projectDir.toPath().resolve("gh-args.txt")));
        assertFalse(Files.exists(projectDir.toPath().resolve(".github/workflows/publish-fixture.yml")));
        assertTrue(read(projectDir.toPath().resolve(".gitignore")).isEmpty());
    }

    @Test
    public void configurePublishWritesOnlyMissingGpgSecretsWhenCentralTargetNotOverwriting() throws Exception {
        File projectDir = createGradlePluginProject("");
        Path gpgKeyFile = projectDir.toPath().resolve("gpg-private.asc");
        write(gpgKeyFile, "private-key");
        write(projectDir.toPath().resolve("local.properties"),
                "publish.githubSecrets=true\n"
                        + "publish.publishTarget=central\n"
                        + "publish.githubRepo=OWNER/REPO\n"
                        + "publish.centralNamespace=com.example\n"
                        + "publish.centralPublishingType=user_managed\n"
                        + "publish.mavenCentralUsername=central-user\n"
                        + "publish.mavenCentralPassword=central-password\n"
                        + "publish.gpgKeyFile=" + gpgKeyFile.toAbsolutePath() + "\n"
                        + "publish.signingPassword=signing-password\n");
        File fakeGh = fakeGhScript(projectDir,
                "MAVEN_CENTRAL_USERNAME\nMAVEN_CENTRAL_PASSWORD\nGPG_KEY_CONTENTS\n");

        gradleRunner(projectDir)
                .withArguments(
                        ":fixture:configurePublish",
                        "-PghExecutable=" + fakeGh.getAbsolutePath(),
                        "--stacktrace"
                )
                .build();

        String args = read(projectDir.toPath().resolve("gh-args.txt"));
        assertTrue(args.contains("secret set SIGNING_PASSWORD -R OWNER/REPO"));
        assertFalse(args.contains("secret set GPG_KEY_CONTENTS -R OWNER/REPO"));
    }

    @Test
    public void rollbackPublishSecretsInfersRepoAndRemovesDefaultGeneratedWorkflow() throws Exception {
        File projectDir = createGradlePluginProject(
                "publish.centralNamespace=com.example\n"
                        + "publish.centralPublishingType=user_managed\n");
        Path workflow = projectDir.toPath().resolve(".github/workflows/publish-fixture.yml");
        Files.createDirectories(workflow.getParent());
        write(workflow,
                "# Generated by PublishPlugin configurePublish\n"
                        + "name: Publish Maven\n");
        File fakeGh = fakeGhScript(projectDir, "");

        gradleRunner(projectDir)
                .withArguments(
                        ":fixture:rollbackPublishSecrets",
                        "-PghExecutable=" + fakeGh.getAbsolutePath(),
                        "-PremoveGeneratedWorkflow=true",
                        "--stacktrace"
                )
                .build();

        Path ghArgs = projectDir.toPath().resolve("gh-args.txt");
        assertTrue("rollback should infer the repository and call gh", Files.exists(ghArgs));
        String args = read(ghArgs);
        assertTrue(args.contains("secret delete MAVEN_CENTRAL_USERNAME -R OWNER/REPO"));
        assertTrue(args.contains("secret delete SIGNING_KEY_ID -R OWNER/REPO"));
        assertFalse(Files.exists(workflow));
    }

    private File createGradlePluginProject(String localProperties) throws Exception {
        File root = temporaryFolder.newFolder("project");
        write(root.toPath().resolve("settings.gradle"), "pluginManagement {\n"
                + "    repositories { google(); mavenCentral(); gradlePluginPortal() }\n"
                + "}\n"
                + "dependencyResolutionManagement {\n"
                + "    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)\n"
                + "    repositories { google(); mavenCentral() }\n"
                + "}\n"
                + "rootProject.name = 'one-click-fixture'\n"
                + "include ':fixture'\n");
        write(root.toPath().resolve("local.properties"), localProperties);
        write(root.toPath().resolve(".gitignore"), "");
        Files.createDirectories(root.toPath().resolve(".git"));
        write(root.toPath().resolve(".git/config"), "[remote \"origin\"]\n"
                + "    url = git@github.com:Entertech/one-click-fixture.git\n");

        Path fixtureDir = root.toPath().resolve("fixture");
        Files.createDirectories(fixtureDir.resolve("src/main/java/com/example/fixture"));
        write(fixtureDir.resolve("src/main/java/com/example/fixture/FixturePlugin.java"),
                "package com.example.fixture;\n"
                        + "import org.gradle.api.Plugin;\n"
                        + "import org.gradle.api.Project;\n"
                        + "public class FixturePlugin implements Plugin<Project> {\n"
                        + "    public void apply(Project project) { }\n"
                        + "}\n");
        write(fixtureDir.resolve("build.gradle"), "plugins {\n"
                + "    id 'java-gradle-plugin'\n"
                + "    id 'cn.entertech.publish'\n"
                + "}\n"
                + "PublishInfo {\n"
                + "    groupId = 'com.example'\n"
                + "    artifactId = 'fixture'\n"
                + "    version = '1.0.0'\n"
                + "    pluginId = 'com.example.fixture'\n"
                + "    implementationClass = 'com.example.fixture.FixturePlugin'\n"
                + "}\n");
        return root;
    }

    private static GradleRunner gradleRunner(File projectDir) {
        return GradleRunner.create()
                .withGradleVersion(TEST_GRADLE_VERSION)
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .forwardOutput();
    }

    private static void write(Path path, String value) throws Exception {
        Files.write(path, value.getBytes(StandardCharsets.UTF_8));
    }

    private static String read(Path path) throws Exception {
        return new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
    }

    private static File fakeGhScript(File root, String listOutput) throws Exception {
        File script = root.toPath().resolve("fake-gh.sh").toFile();
        String rootPath = root.getAbsolutePath();
        Files.write(script.toPath(), ("#!/bin/sh\n"
                + "echo \"$@\" >> \"" + rootPath + "/gh-args.txt\"\n"
                + "cat > \"" + rootPath + "/gh-stdin.txt\"\n"
                + "if [ \"$1\" = \"repo\" ] && [ \"$2\" = \"view\" ]; then\n"
                + "  printf 'OWNER/REPO\\n'\n"
                + "  exit 0\n"
                + "fi\n"
                + "if [ \"$1\" = \"secret\" ] && [ \"$2\" = \"list\" ]; then\n"
                + "  printf '" + listOutput.replace("\n", "\\n") + "'\n"
                + "  exit 0\n"
                + "fi\n"
                + "exit 0\n").getBytes(StandardCharsets.UTF_8));
        assertTrue(script.setExecutable(true));
        return script;
    }
}
